### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by wmertens** [fcharron/last-cursor-position#11]
[Enter steps to reproduce below:]

Sorry, it's the first time I use it, no real repro steps...

**Atom Version**: 0.180.0
**System**: Mac OS X 10.10.2
**Thrown From**: [last-cursor-position](https://github.com/fcharron/last-cursor-position) package, v0.7.0

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:378:25)
  at /Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/pane.js:348:20)
  at Pane.module.exports.Pane.activateItem (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/pane.js:327:14)
  at Object.module.exports.previous (/Users/wmertens/.atom/packages/last-cursor-position/lib/last-cursor-position.coffee:86:39)
  at atom-workspace.disposables.add.atom.commands.add.last-cursor-position:previous (/Users/wmertens/.atom/packages/last-cursor-position/lib/last-cursor-position.coffee:59:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
  5x -0:44.5 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:42.4 core:paste (atom-text-editor.editor.is-focused)
     -0:40.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:39.6 core:move-right (atom-text-editor.editor.is-focused)
     -0:39.1 core:select-up (atom-text-editor.editor.is-focused)
     -0:38.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:37.7 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:36.6 core:move-down (atom-text-editor.editor.is-focused)
     -0:35.9 core:move-left (atom-text-editor.editor.is-focused)
     -0:35.5 refactor:done (atom-text-editor.editor.is-focused)
     -0:35.5 editor:newline (atom-text-editor.editor.is-focused)
     -0:33.8 core:move-right (atom-text-editor.editor.is-focused)
  6x -0:29.7 core:select-down (atom-text-editor.editor.is-focused)
     -0:27.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.8 window:decrease-font-size (atom-text-editor.editor.is-focused)
     -0:05.5 last-cursor-position:previous (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "preview-plus",
      "my-package",
      "preview-tabs",
      "tabs",
      "tree-view",
      "open-last-project"
    ],
    "projectHome": "~/Documents/Projects"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus-async, v0.22.0
coffee-lint, v0.7.3
coffee-navigator, v0.0.15
coffee-refactor, v0.6.2
indent-toggle-on-paste, v0.1.1
js-refactor, v0.3.0
language-coffee-script-angular, v2.2.0
language-jade, v0.3.0
language-javascript-semantic, v0.1.0
last-cursor-position, v0.7.0
linter, v0.11.1
linter-tidy, v1.0.0
minimap, v4.2.2
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-selection, v4.0.1
nix, v2.1.0
preview, v0.13.4
project-manager, v1.15.5
refactor, v0.4.1
sublime-tabs, v0.4.9
web-browser, v1.3.0

# Dev
No dev packages
```

**Comment by fcharron** [comment]
I tried for a while, but I cannot reproduce the issue. If you reproduce it, can you try and give me repro steps?

Thanks

**Comment by wmertens** [comment]
Ok will do :) Must say that I haven't seen it lately.

**Comment by fcharron** [comment]
Can't repro with current version. Will reopen if we see it again.

**Comment by patrickjtoy** [comment]
Just got this same error. It occurred when:
1. Working with two panes...
3. Click inside right pane...
2. Click inside the left pane...
3. Using goto definition...
4. Using the keyboard shortcut (Alt + -) to return to previous location
5. Crashes with the above error.

I was able to reproduce the issue three times with the steps above.

**Comment by fcharron** [comment]
This one came first, but I just updated #17, so let's use that one from now on.
