### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by jinksong** [fcharron/last-cursor-position#17]
[Enter steps to reproduce below:]
1. Open tree panes and load different files
2. Move around with ALT+- / _
3. (Optional) When settings window is opened, the symptom becomes even worse. One of the source code content occupies 'Settings' window and the original source code window goes completely blank.

**Atom Version**: 0.190.0
**System**: linux 3.13.0-48-generic
**Thrown From**: [last-cursor-position](https://github.com/fcharron/last-cursor-position) package, v0.8.0
### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /usr/share/atom/resources/app/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (/usr/share/atom/resources/app/src/item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app/src/pane-container.js:369:25)
  at /usr/share/atom/resources/app/src/pane-container.js:357:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:305:20)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:276:14)
  at Object.module.exports.previous (/ml/Users/MAGICLEAP/jsong/.atom/packages/last-cursor-position/lib/last-cursor-position.coffee:86:39)
  at atom-workspace.disposables.add.atom.commands.add.last-cursor-position:previous (/ml/Users/MAGICLEAP/jsong/.atom/packages/last-cursor-position/lib/last-cursor-position.coffee:59:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:242:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:180:20)

```
### Commands

```
     -6:01.2 pane:show-next-item (atom-text-editor.editor)
     -5:59.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -5:58.5 pane:show-next-item (atom-text-editor.editor)
     -5:58.3 core:close (atom-text-editor.editor.is-focused)
     -5:36.5 core:confirm (atom-text-editor.editor.mini)
  2x -0:50.8 last-cursor-position:previous (atom-text-editor.editor)
  2x -0:49.0 last-cursor-position:next (atom-text-editor.editor)
     -0:41.9 window:decrease-font-size (atom-text-editor.editor)
  5x -0:39.9 last-cursor-position:previous (atom-text-editor.editor)
 12x -0:37.3 last-cursor-position:next (atom-text-editor.editor)
 25x -0:35.0 last-cursor-position:previous (atom-text-editor.editor)
 31x -0:30.9 last-cursor-position:next (atom-text-editor.editor)
     -0:13.1 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -0:07.3 core:move-down (atom-text-editor.editor.mini)
     -0:07.1 core:confirm (atom-text-editor.editor.mini)
 15x -0:03.7 last-cursor-position:previous (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "whitespace"
    ],
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v2.6.1
autocomplete-plus, v2.9.0
last-cursor-position, v0.8.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by fcharron** [comment]
This is more complicated than I thought it would be. Working on it when I have time, but in the meantime working with panes will probably cause issues with the package.

**Comment by lukeaus** [comment]
Can confirm this is still an issue

**Comment by danilo-helabs** [comment]
+1

**Comment by Dbuggerx** [comment]
+1

**Comment by a7madgamal** [comment]
+1

**Comment by harai** [comment]
+1

**Comment by jjm340** [comment]
+1

**Comment by dorellang** [comment]
+1

**Comment by guyca** [comment]
+1

**Comment by proclaim** [comment]
+1

**Comment by aramk** [comment]
+1

**Comment by haharicky** [comment]
+1

**Comment by Koshmaar** [comment]
+1

**Comment by koyedele** [comment]
+1

**Comment by fcharron** [comment]
Need help for this one. Anyone has a clue?

**Comment by shotgundebugging** [comment]
+1
