### ISSUE TITLE
Uncaught TypeError: Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by kschaper** [fcharron/last-cursor-position#8]
Uncaught TypeError: Cannot read property 'model' of undefined

**Atom Version**: 0.156.0
**System**: Mac OS X 10.9.5
**Thrown From**: [last-cursor-position](https://github.com/fcharron/last-cursor-position) package, v0.5.0

### Steps To Reproduce

1. open some tabs, in my case 5
2. open command palette
3. Pane: close

### Stack Trace

```
At /Users/kaischaper/.atom/packages/last-cursor-position/lib/last-cursor-position.coffee:32

TypeError: Cannot read property 'model' of undefined
  at /Users/kaischaper/.atom/packages/last-cursor-position/lib/last-cursor-position.coffee:32:89
  at Array.filter (native)
  at atom-workspace.<anonymous> (/Users/kaischaper/.atom/packages/last-cursor-position/lib/last-cursor-position.coffee:32:46)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by fcharron** [comment]
no news from op, will close
